### ISSUE TITLE
with an explanation strategy with 2 explainers, the 2d explainer does not return any result in the chatbot

### ISSUE THREAD

**Issue by anneliret** [isee4xai/iSeeDialogManager#29] opened 2024-02-02 11:01 UTC
I've tried on radiology case and sensor anomaly case, 
in sensor anomaly, the "transparency" goal of Auditor persona is mapped to 2 explainers : integratedGradients and nearestNeighbours. on the chatbot, the 1st explainer returns a result, then on the chatbot I ask "I would like another explanation". but then the chatbot is getting stuck (the 3 dotted lines).
same issue with radiology , in Clinician persona and Transparency goal, the 1st explainer works (integratedGradients) but not the 2d one (nearestNeighbours).

**Comment by anjanaw** [comment] 2024-02-02 16:13
Sensor Anomaly - issue reproduced and there is a 500 error coming from the iSeeExplainerLibrary server. Please check with Jesus. 
Jiva Fracture Detection - issue not reproduced. Nearest Neighbour returns an explanation. see screenshot attached. 

<img width="959" alt="Screenshot 2024-02-02 at 16 11 50" src="https://github.com/isee4xai/iSeeDialogManager/assets/233262/0e36ced5-bbdb-45be-b0b2-355ea1bafd45">
<img width="959" alt="Screenshot 2024-02-02 at 16 12 25" src="https://github.com/isee4xai/iSeeDialogManager/assets/233262/17343bec-9b35-4919-84f6-4f997fbcbdaa">

**Comment by anjanaw** [comment] 2024-02-02 17:24
Bosch Nearest Neighbour is failing due to Out of Memory issue. The sample dataset is too big. will be fixed by uploading a smaller dataset by Jesus. Closing issue.

**Closed by anjanaw** 2024-02-02 17:24 UTC
